###########################################
#                                         #
#             KLQuickGuide                #
#                                         #
###########################################

# !!! НЕ ИСПОЛЬЗУЙТЕ & / ИСПОЛЬЗУЙТЕ ЭТОТ СИМВОЛ: § !!!
# !!! DO NOT USE & / USE THIS CHARACTER: § !!! 

# !!! НЕ УДАЛЯЙТЕ 15 СТРОКУ!!!
# !!! DO NOT DELETE LINE 15 !!!

plugin:
  # Вкл./Выкл. плагин / Turn plugin on/off
  enabled: true 
  prefix: '§8[§dQuick§5Guide&8]'
  # Координаты первой локации / First location coordinates
  x1: 0
  y1: 0
  z1: 0
  yaw1: 0.0
  pitch1: 0.0

# Координаты второй локации / 2-nd location coordinates
  x2: 0
  y2: 0
  z2: 0
  yaw2: 0.0
  pitch2: 0.0

# Третьей локации / Third location coordinates
  x3: 0
  y3: 0
  z3: 0
  yaw3: 0.0
  pitch3: 0.0

# Спавна / Spawn coordinates
  xSpawn: 0
  ySpawn: 0
  zSpawn: 0
  yawSpawn: 0.0
  pitchSpawn: 0.0

# Сообщения при телепорте / Messages when teleported
  msg1: 'Message1'
  msg2: 'Message2'
  msg3: 'Message3'
  endmsg: 'End message'